sepp:
  local:
    n32:
      fqdn: "local-sepp.example.com"
      host: "localhost"
      port: "1236"
      tls:
        cert: "certs/n32Server.crt"
        key: "certs/n32Server.key"
        ca: "certs/ca.crt"
    sbi:
      fqdn: "local-sbi.example.com"
      host: "localhost"
      port: "1237"
      tls:
        cert: "certs/sbiServer.crt"
        key: "certs/sbiServer.key"
        ca: "certs/ca.crt"
  remote:
    url: "https://127.0.0.1:1235"
    tls:
      cert: "certs/client.crt"
      key: "certs/client.key"
      ca: "certs/ca.crt"
