sepp:
  securityCapability: "TLS"
  local:
    n32:
      fqdn: "https://sepp-plmn-a:1231"
      host: "sepp-plmn-a"
      port: "1231"
      tls:
        cert: "e2etests/plmnA/certs/n32Server.crt"
        key: "e2etests/plmnA/certs/n32Server.key"
        ca: "e2etests/plmnA/certs/ca.crt"
    sbi:
      fqdn: "https://sepp-plmn-a:1232"
      host: "sepp-plmn-a"
      port: "1232"
      tls:
        cert: "e2etests/plmnA/certs/sbiServer.crt"
        key: "e2etests/plmnA/certs/sbiServer.key"
        ca: "e2etests/plmnA/certs/ca.crt"
  remote:
    url: "https://sepp-plmn-a:1233"
    tls:
      cert: "e2etests/plmnA/certs/client.crt"
      key: "e2etests/plmnA/certs/client.key"
      ca: "e2etests/plmnA/certs/ca.crt"
