sepp:
  securityCapability: "TLS"
  local:
    n32:
      fqdn: "https://0.0.0.0:1233"
      host: "0.0.0.0"
      port: "1233"
      tls:
        cert: "/etc/sepp/certs/n32Server.crt"
        key: "/etc/sepp/certs/n32Server.key"
        ca: "/etc/sepp/certs/ca.crt"
    sbi:
      fqdn: "local-sbi.example.com"
      host: "0.0.0.0"
      port: "1234"
      tls:
        cert: "/etc/sepp/certs/sbiServer.crt"
        key: "/etc/sepp/certs/sbiServer.key"
        ca: "/etc/sepp/certs/ca.crt"
  remote:
    url: "https://0.0.0.0:1231"
    tls:
      cert: "/etc/sepp/certs/client.crt"
      key: "/etc/sepp/certs/client.key"
      ca: "/etc/sepp/certs/ca.crt"
