sepp:
  local:
    n32:
      fqdn: "local-sepp.example.com"
      host: "localhost"
      port: "1234"
      tls:
        cert: "/etc/sepp/certs/server.crt"
        key: "/etc/sepp/certs/server.key"
        ca: "/etc/sepp/certs/ca.crt"
    sbi:
      fqdn: "local-sbi.example.com"
      host: "localhost"
      port: "1235"
      tls:
        cert: "/etc/sepp/certs/server.crt"
        key: "/etc/sepp/certs/server.key"
        ca: "/etc/sepp/certs/ca.crt"
  remote:
    url: "https://remote-sepp.example.com"
    tls:
      cert: "/etc/sepp/certs/server.crt"
      key: "/etc/sepp/certs/server.key"
      ca: "/etc/sepp/certs/ca.crt"
