name: sepp
base: core22
version: '0.1'
summary: An open source implementation of the 5G Security Edge Protection Proxy
description: |
  An open source implementation of the 5G Security Edge Protection Proxy (SEPP) 
  that uses the TLS Security Capability to handle the forwarding of Network Functions' 
  HTTP/2 messages.

grade: stable
confinement: strict

apps:
  sepp:
    command: bin/sepp -config sepp.yaml

parts:
  sepp:
    source: .
    plugin: go
    build-snaps:
      - go/1.21/stable

  config:
    source: .
    plugin: dump
    organize:
      config.yaml: sepp.yaml
