name: Integration tests

on:
    workflow_call:

jobs:
    integration-tests:
        runs-on: ubuntu-22.04
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Download rock artifact
          uses: actions/download-artifact@v4
          with:
            name: rock

        - name: Import rock artifact
          run: |
            image_name="$(yq '.name' rockcraft.yaml)"
            echo "image_name=${image_name}" >> $GITHUB_ENV
            version="$(yq '.version' rockcraft.yaml)"
            echo "version=${version}" >> $GITHUB_ENV
            rock_file=$(ls *.rock | tail -n 1)
            sudo skopeo \
              --insecure-policy \
              copy \
              oci-archive:"${rock_file}" \
              docker-daemon:"${image_name}-rock:test"

        - name: Setup Go
          uses: actions/setup-go@v5
          with:
            go-version-file: "e2etests/go.mod"

        - name: Run tests
          run: |
            go test -v ./e2etests
